spring:
  redis:
    host: 81.69.34.46
    port: 6379
    password: chengwuchao1314
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
        timeout: 5000ms
