spring:
  redis:
    host: redis-6271faf7-ed2e-4e4d-8f8d-bc2091089089.cn-east-3.yzsci.cn
    port: 6379
    password: o9k3e3BDcfwAofK9wokn
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
        timeout: 5000ms
